site_name: xorcery
site_author: Rickard Oberg
site_url: https://cantara.github.io/xorcery
site_dir: target/site/
repo_url: https://github.com/Cantara/xorcery
edit_uri: ''
use_directory_urls: false
theme:
    name: readthedocs
    custom_dir: theme/
    highlightjs: false
markdown_extensions:
  - admonition
  - codehilite
  - def_list
  - toc:
      permalink: true
nav:
  - 'index.md'
  - Usage:
    - 'usage/index.md'
    - 'usage/configuration.md'
    - 'usage/dependencyinjection.md'
    - 'usage/servicediscovery.md'
    - 'usage/reactivestreams.md'
    - 'usage/eventsourcing.md'
  - JavaDocs:
      - 'JavaDocs for all modules': apidocs/index.html
  - Development:
    - 'development/index.md'
